model:
  base_learning_rate: 5.0e-5
  target: ldm.models.diffusion.teeth_dreamer.TeethDreamer
  params:
    view_num: 8
    image_size: 256
    cfg_scale: 2.0
    output_num: 8
    batch_view_num: 4
    finetune_unet: false
    finetune_projection: true
    drop_conditions: false
    clip_image_encoder_path: ckpt/ViT-L-14.pt

    scheduler_config: # 10000 warmup steps
      target: ldm.lr_scheduler.LambdaLinearScheduler
      params:
        warm_up_steps: [ 100 ]
        cycle_lengths: [ 100000 ]
        f_start: [ 0.02 ]
        f_max: [ 1.0 ]
        f_min: [ 1.0 ]

    unet_config:
      target: ldm.models.diffusion.sync_dreamer_attention.DepthWiseAttention
      params:
        volume_dims: [64, 128, 256, 512]
        image_size: 32
        in_channels: 20
        out_channels: 4
        model_channels: 320
        attention_resolutions: [ 4, 2, 1 ]
        num_res_blocks: 2
        channel_mult: [ 1, 2, 4, 4 ]
        num_heads: 8
        use_spatial_transformer: True
        transformer_depth: 1
        context_dim: 768
        use_checkpoint: True
        legacy: False

data:
  target: ldm.data.teeth_dreamer.TeethDreamerDataset
  params:
    target_dir: /public/home/v-xuchf/Data/Teeth_recon/rendering/256/target # renderings of target views
    input_dir: /public/home/v-xuchf/Data/Teeth_recon/rendering/256/input # renderings of input views
    uid_set_pkl: /public/home/v-xuchf/Data/Teeth_recon/rendering/256/mv-splits.pkl # a list of uids
    validation_dir: /public/home/v-xuchf/Data/Teeth_recon/rendering/256/input # directory of validation data
    test_set_npy: /public_bme/data/v-xuchf/test/splits.npy
    test_dir: /public_bme/data/v-xuchf/test/real
    batch_size: 16 # change from 60
    num_workers: 4
    normal_predict: true
    single_cond: false
    val_crop_size: -1

lightning:
  modelcheckpoint:
    params:
      every_n_train_steps: 200 # we will save models every 1k steps
  callbacks:
    {}

  trainer:
    benchmark: True
    val_check_interval: 1000 # we will run validation every 1k steps, the validation will output images to <log_dir>/<images>/val
    num_sanity_val_steps: 0
    check_val_every_n_epoch: null
    max_epochs: -1
